import type {
  ClinicalProtocolDraft,
  EvaluationResult,
  EvidenceItem,
  Hypothesis,
  MoleculeCandidate,
  Project,
  RegulatoryCheck,
  Report,
  ReportType,
  SafetyFlag,
  TargetCandidate,
  WorkflowRun,
  BusinessAssumptions,
} from '@/types'
import {
  CLINICAL_DISCLAIMER,
  HUMAN_RESPONSIBILITY_STATEMENT,
  NO_SYNTHESIS_NOTICE,
  SAFETY_POLICY_VERSION,
} from '@/lib/constants'
import { RECOMMENDATION_LABEL } from '@/lib/scoring'
import { computeBusinessValue } from '@/lib/business'

export interface ReportCtx {
  project: Project
  evidence: EvidenceItem[]
  targets: TargetCandidate[]
  hypotheses: Hypothesis[]
  molecules: MoleculeCandidate[]
  safetyFlags: SafetyFlag[]
  clinical?: ClinicalProtocolDraft
  regulatory: RegulatoryCheck[]
  evaluations: EvaluationResult[]
  workflow?: WorkflowRun
  business: BusinessAssumptions
}

export const REPORT_META: Record<ReportType, { title: string; subtitle: string }> = {
  judge_demo: { title: 'Judge Demo Report', subtitle: '심사위원 데모 리포트' },
  technical_architecture: { title: 'Technical Architecture Report', subtitle: '기술 아키텍처 리포트' },
  candidate_package: { title: 'Scientific Candidate Package', subtitle: '과학적 후보 패키지' },
  ethics_safety: { title: 'Ethics & Safety Appendix', subtitle: '윤리·안전 부록' },
  evaluation_benchmark: { title: 'Evaluation Benchmark Report', subtitle: '평가 벤치마크 리포트' },
  business_value: { title: 'Business Value Summary', subtitle: '사업 가치 요약' },
  full_proposal: { title: 'Full Competition Proposal Draft', subtitle: '전체 공모 제안서 초안' },
}

function stamp(project: Project): string {
  const now = new Date().toISOString()
  return [
    `> **Project:** ${project.name}  `,
    `> **Mode:** ${project.mode === 'demo' ? 'Demo Mode (all scientific outputs are Demo Simulation unless labeled otherwise)' : 'Real Tool Mode'}  `,
    `> **Generated:** ${now}  `,
    `> **Safety policy:** ${SAFETY_POLICY_VERSION}`,
  ].join('\n')
}

function disclaimerBlock(): string {
  return [
    '---',
    '### Human Responsibility & Disclaimer',
    `> ${HUMAN_RESPONSIBILITY_STATEMENT}`,
    '>',
    `> ${CLINICAL_DISCLAIMER}`,
    '>',
    '> Generated by HelixForge AI for expert review. All AI-generated outputs require human verification.',
  ].join('\n')
}

function evidenceTable(ev: EvidenceItem[]): string {
  const head = '| ID | Source | Direction | Verification | Confidence | Claim |\n|---|---|---|---|---|---|'
  const rows = ev
    .map((e) => `| ${e.id} | ${e.sourceName} | ${e.evidenceDirection} | ${e.verificationStatus} | ${(e.confidence * 100).toFixed(0)}% | ${e.claim.replace(/\|/g, '/')} |`)
    .join('\n')
  return `${head}\n${rows}`
}

function candidateTable(mols: MoleculeCandidate[]): string {
  const head = '| Candidate | Valid | Binding | ADMET | QED | Lipinski | SA | Safety | Composite | Recommendation |\n|---|---|---|---|---|---|---|---|---|---|'
  const rows = mols
    .map((m) => `| ${m.label} | ${m.validityStatus} | ${m.bindingScore || '—'} | ${(m.admetScore * 100).toFixed(0)}% | ${m.qed.toFixed(2)} | ${m.lipinskiPass ? 'pass' : `${m.lipinskiViolations} viol`} | ${m.saScore} | ${m.safetyStatus} | ${m.compositeScore || '—'} | ${RECOMMENDATION_LABEL[m.recommendation].label} |`)
    .join('\n')
  return `${head}\n${rows}`
}

function metricTable(rows: EvaluationResult[]): string {
  const head = '| Benchmark | Metric | Value | Target | Status |\n|---|---|---|---|---|'
  const body = rows
    .map((r) => `| ${r.benchmarkName} | ${r.metricName} | ${r.value}${r.unit ? ' ' + r.unit : ''} | ${r.target}${r.unit ? ' ' + r.unit : ''} | ${r.status.toUpperCase()} |`)
    .join('\n')
  return `${head}\n${body}`
}

const ARCH_STAGES = [
  'PLANNING → EVIDENCE_MINING → DISEASE_MODELING → TARGET_RANKING → HYPOTHESIS_GENERATION',
  '→ MOLECULE_GENERATION → STRUCTURE_VALIDATION → DOCKING/BINDING → ADMET_SCREENING → SYNTHESIS_FEASIBILITY',
  '→ SAFETY_AUDIT → CRITIC_REVIEW → (REVISION_LOOP) → CLINICAL_STRATEGY → REGULATORY_REVIEW → EVALUATION → REPORT_GENERATION → COMPLETE',
]

export function generateReport(type: ReportType, ctx: ReportCtx): Report {
  const { project } = ctx
  let md = ''
  const title = REPORT_META[type].title
  const top = ctx.molecules
    .filter((m) => m.recommendation === 'advance')
    .sort((a, b) => b.compositeScore - a.compositeScore)[0]
  const bv = computeBusinessValue(ctx.business)

  const header = `# ${title}\n## HelixForge AI — ${REPORT_META[type].subtitle}\n\n${stamp(project)}\n`

  if (type === 'judge_demo') {
    md = `${header}
## 1. Executive Summary
HelixForge AI is an **agentic drug-discovery operating system** — not a chatbot. For **${project.disease}** (${project.indication}), 17 specialized agents autonomously decomposed the goal into a ${ARCH_STAGES.length ? '16' : ''}-stage DAG, called scientific tools (or labeled demo adapters), validated outputs, **caught and corrected injected errors**, blocked unsafe candidates, and produced this auditable report. Top candidate for expert review: **${top?.label ?? '—'}** (composite ${top?.compositeScore ?? '—'}/100).

## 2. Problem Definition
- **Disease / indication:** ${project.disease} — ${project.indication}
- **Patient population:** ${project.patientPopulation}
- **Unmet need:** ${project.unmetNeed}
- **Discovery goal:** ${project.discoveryGoal}

## 3. Why an Agentic System Is Needed
Drug discovery spans literature triage, target prioritization, molecule optimization, safety, and clinical/regulatory reasoning — each with different tools, data, and failure modes. A single prompt cannot integrate, validate, and self-correct across these. HelixForge decomposes the problem, routes subtasks to specialized tool-using agents, and runs a critic/verifier loop.

## 4. Multi-Agent Architecture
Orchestrator + 16 specialists (Evidence Miner, Target Scout, Hypothesis Generator, Molecular Design, Cheminformatics Validator, Binding & Structure, ADMET & Toxicology, Synthesis Feasibility, Safety Auditor, Clinical Strategy, Regulatory Reviewer, Business Analyst, Evaluation Harness, Critic/Verifier, Report Builder, Disease Biology).

## 5. Tool Integration
Adapters for literature (PubMed/Europe PMC/Semantic Scholar/CrossRef), biology (Open Targets/UniProt/ChEMBL/KG), chemistry (RDKit/REINVENT4/ChemProp/TDC), structure/docking (PDB/AlphaFold/Vina/DiffDock/Boltz), synthesis feasibility (AiZynthFinder/ASKCOS — feasibility score only), clinical/regulatory (ClinicalTrials.gov/FDA·MFDS RAG), and safety screens. Missing tools fall back to Demo Mode, never faking a real result.

## 6. End-to-End Workflow
\`\`\`
${ARCH_STAGES.join('\n')}
\`\`\`

## 7. Scientific Rationale
${ctx.hypotheses.map((h) => `- **${h.targetSymbol}:** ${h.statement} _(confidence ${(h.confidence * 100).toFixed(0)}%; ${h.limitations})_`).join('\n')}

## 8. Candidate Ranking Summary
${candidateTable(ctx.molecules)}

## 9. Safety & Ethics Gate
- Blocked / quarantined: **${ctx.safetyFlags.filter((f) => f.status === 'BLOCKED').length}**; review-required: **${ctx.safetyFlags.filter((f) => f.status === 'REVIEW_REQUIRED').length}**.
- ${NO_SYNTHESIS_NOTICE}
- Fabricated citations are rejected; toxicity is screened defensively, never optimized.

## 10. Clinical / Regulatory Strategy
${ctx.clinical ? `Draft TPP for **${ctx.clinical.candidateLabel}**: ${ctx.clinical.phase}. ${CLINICAL_DISCLAIMER}` : 'Not generated.'}

## 11. Evaluation Metrics
${metricTable(ctx.evaluations.slice(0, 10))}

## 12. Business & Social Value
- Estimated time saved/month: **${bv.timeSavedHours.toLocaleString()} h**
- Estimated cost saved/month: **$${bv.costSaved.toLocaleString()}**
- ${bv.qualitative}

## 13. Limitations
In-silico decision support only. Demo Simulation values are not real database/wet-lab results. No wet-lab validation performed.

## 14. Future Roadmap
Real-tool wiring (RDKit/TDC/REINVENT4 workers), RAG over live guidance corpora, learned composite scorer, tool-router cost reduction, human-in-the-loop checkpoints.

## 15. Audit Appendix
Workflow ${ctx.workflow?.id ?? '—'}: ${ctx.workflow?.toolRunCount ?? 0} tool runs · ${ctx.workflow?.revisionCount ?? 0} revisions · ${ctx.workflow?.errorCount ?? 0} caught errors · est. cost $${ctx.workflow?.totalEstimatedCost ?? 0}. Full event trace exported in JSON.

${disclaimerBlock()}
`
  } else if (type === 'technical_architecture') {
    md = `${header}
## 1. System Overview
Client-side agentic workbench (React + TypeScript). Deterministic Demo Mode + Real Tool adapter layer. State machine drives the pipeline; every step is logged to an observable audit trail (no hidden chain-of-thought).

## 2. Agents
17 agents (1 orchestrator + 16 specialists), each with role, tools, inputs/outputs, and validation rules.

## 3. State Machine
\`IDLE → PROJECT_CREATED → PLANNING → … → REPORT_GENERATION → COMPLETE\`, with \`REVISION_LOOP\`, \`BLOCKED\`, and \`ERROR\` branches. Each stage records status, agents, tool calls, input/output summary, validation, confidence, and timestamp.

## 4. Tool Adapters
Common shape: \`isConfigured / run / validateOutput / fallback / exampleOutput / safetyNotes\`. Real Tool Mode calls external services; unconfigured tools fall back to Demo, labeled as fallback.

## 5. Data Model
Project · WorkflowRun · AgentRun · ToolRun · AuditEvent · EvidenceItem · TargetCandidate · Hypothesis · MoleculeCandidate · SafetyFlag · ClinicalProtocolDraft · RegulatoryCheck · EvaluationResult · Report · TrainingJob.

## 6. Scoring Formulas
Target Opportunity Score and Molecule Composite Score are transparent, weighted, editable, and normalized to 0–100, with explicit safety and uncertainty penalties.

## 7. Safety Policy (${SAFETY_POLICY_VERSION})
Citation verification · no fabricated data · prompt/model logging · hazardous-material screening · toxicity/dual-use screening · human responsibility · medical/regulatory disclaimer. ${NO_SYNTHESIS_NOTICE}

## 8. Evaluation Harness
Rediscovery, molecule generation, ADMET, docking/enrichment, agent, and safety metric modules.

## 9. Deployment Plan
Static SPA now; Python workers (RDKit/TDC/REINVENT4/docking) behind the adapter interface; vector DB for guidance RAG; optional Postgres schema mirrors the data model.

## 10. Extension Plan
Swap demo adapters for real ones without UI changes; add human-review checkpoints, project memory, comparison & scenario modes.

${disclaimerBlock()}
`
  } else if (type === 'candidate_package') {
    md = `${header}
## 1. Disease & Target Rationale
${project.disease} — top target **${ctx.targets[0]?.symbol}** (${ctx.targets[0]?.score}/100). ${ctx.targets[0]?.rationale}

## 2. Hypothesis
${ctx.hypotheses.map((h) => `- ${h.statement}`).join('\n')}

## 3. Candidate Molecules
${candidateTable(ctx.molecules.filter((m) => m.validityStatus === 'valid'))}

## 4. Property Table (top candidate)
${top ? `MW ${top.descriptors.mw} · logP ${top.descriptors.logP} · HBD ${top.descriptors.hbd} · HBA ${top.descriptors.hba} · TPSA ${top.descriptors.tpsa} · QED ${top.qed}` : '—'}

## 5. ADMET Risk
${top ? `hERG ${top.hERG.toFixed(2)} · Ames ${top.Ames.toFixed(2)} · DILI ${top.DILI.toFixed(2)} · uncertainty ${top.uncertainty.toFixed(2)}` : '—'}

## 6. Binding Estimate
${top ? `${top.bindingScore} kcal/mol (Demo Simulation) · pose confidence ${(top.poseConfidence * 100).toFixed(0)}%` : '—'}

## 7. Safety Status
${ctx.safetyFlags.length} flag(s) recorded. Blocked candidates cannot advance.

## 8. Synthetic Feasibility Summary
${top ? `Feasibility: ${top.synthesisFeasibility} · route confidence ${(top.routeConfidence * 100).toFixed(0)}% · complexity ${(top.estimatedComplexity * 100).toFixed(0)}%. ${NO_SYNTHESIS_NOTICE}` : NO_SYNTHESIS_NOTICE}

## 9. Recommendation
${top ? `${top.label}: ${RECOMMENDATION_LABEL[top.recommendation].label}.` : 'No candidate met the advance threshold.'}

## 10. Expert Review Checklist
- [ ] Confirm target rationale & evidence quality
- [ ] Independent ADMET / tox review
- [ ] Structural & IP novelty assessment
- [ ] Synthetic route feasibility (expert-led, out of this system's scope)
- [ ] Regulatory gap closure

${disclaimerBlock()}
`
  } else if (type === 'ethics_safety') {
    md = `${header}
## 1. AI-Generated Data Policy
All AI-generated values are labeled **Demo Simulation** and never presented as real database or wet-lab results.

## 2. Citation Verification
Every reference is cross-checked. Fabricated/unresolvable identifiers (e.g., the injected \`PMID:00000000\`) are demoted to *failed* and excluded from verified evidence.

## 3. Prompt / Model / Settings Log
Orchestrator model, effort, temperature, tool calls, inputs/outputs, and citations are recorded in the audit trail.

## 4. Hazard Screening
Controlled, explosive, and highly toxic classes are blocked. ${ctx.safetyFlags.filter((f) => f.status === 'BLOCKED').length} candidate(s) blocked this run.

## 5. No-Synthesis-Route Policy
${NO_SYNTHESIS_NOTICE} No reagents, conditions, purification, or procedural steps are produced.

## 6. Human Final Responsibility
${HUMAN_RESPONSIBILITY_STATEMENT}

## 7. Medical / Regulatory Disclaimer
${CLINICAL_DISCLAIMER}

## 8. Audit Trail Export
Full chronological event trace (agent, tool, input/output summary, validation, safety, timestamp) is exportable as JSON. Hidden chain-of-thought is never exposed — only the observable process trace.

${disclaimerBlock()}
`
  } else if (type === 'evaluation_benchmark') {
    md = `${header}
## Benchmark Results
${metricTable(ctx.evaluations)}

## Interpretation
Metrics are computed on Demo Simulation data for demonstration. ADMET/docking metrics are illustrative demo values, not validated model performance. Self-correction, citation-verification, and safety-block metrics reflect the actual in-app behavior of the agentic loop.

${disclaimerBlock()}
`
  } else if (type === 'business_value') {
    md = `${header}
## Assumptions
- Literature triage: ${ctx.business.literatureTriageHours} h/workflow
- Target prioritization: ${ctx.business.targetPrioritizationDays} d/workflow
- Molecule screening: ${ctx.business.moleculeScreeningCount} candidates
- Researcher cost: $${ctx.business.costPerResearcherHour}/h
- Workflows/month: ${ctx.business.workflowsPerMonth}
- Est. time saved: ${ctx.business.percentTimeSaved}%
- LLM/tool run cost: $${ctx.business.llmToolRunCost}/workflow

## Estimated Value (ranges, not guarantees)
- Time saved: **~${bv.timeSavedHours.toLocaleString()} h/month**
- Gross cost saved: **~$${bv.grossSaved.toLocaleString()}/month**
- Net of run cost: **~$${bv.costSaved.toLocaleString()}/month**

## Where Human Review Remains Essential
Target/candidate sign-off, ADMET/tox confirmation, synthetic route design, clinical protocol finalization, and all regulatory decisions.

> HelixForge AI does not replace wet-lab validation or expert review. Its value is reducing the search space, documenting rationale, and accelerating candidate prioritization.

${disclaimerBlock()}
`
  } else {
    // full_proposal — concatenate the key sections
    const judge = generateReport('judge_demo', ctx).markdown
    const tech = generateReport('technical_architecture', ctx).markdown
    const ethics = generateReport('ethics_safety', ctx).markdown
    md = `${header}\n\n# Part A — Judge Demo\n${judge}\n\n# Part B — Technical Architecture\n${tech}\n\n# Part C — Ethics & Safety\n${ethics}`
  }

  const jsonAudit = JSON.stringify(
    {
      project: { id: project.id, name: project.name, mode: project.mode, disease: project.disease },
      workflow: ctx.workflow,
      evidenceCount: ctx.evidence.length,
      targets: ctx.targets.map((t) => ({ symbol: t.symbol, score: t.score, rank: t.rank })),
      molecules: ctx.molecules.map((m) => ({ label: m.label, valid: m.validityStatus, composite: m.compositeScore, safety: m.safetyStatus, recommendation: m.recommendation })),
      safetyFlags: ctx.safetyFlags,
      evaluations: ctx.evaluations,
      disclaimer: HUMAN_RESPONSIBILITY_STATEMENT,
      generatedAt: new Date().toISOString(),
    },
    null,
    2,
  )

  return {
    id: `rep-${type}-${Date.now()}`,
    projectId: project.id,
    type,
    title,
    markdown: md,
    jsonAudit,
    createdAt: new Date().toISOString(),
    exportStatus: 'ready',
  }
}
