"""REINVENT4 adapter — config generation + subprocess execution + result parsing.

- create-config: always writes a real REINVENT4 TOML config from the request
  (scoring weights → scoring components). This works with or without REINVENT4
  installed.
- run: executes REINVENT4 via `REINVENT4_PYTHON -m reinvent <config>` or
  `REINVENT4_BIN <config>` if configured. If not configured/installed, returns
  CONFIGURED_BUT_NOT_RUN — never fabricated molecules.
- parse-results: reads generated SMILES and post-validates each with RDKit.

Safety: generation is property/QSAR-guided at a high level; a safety penalty
component is included. No synthesis routes are produced.
"""
from __future__ import annotations

import subprocess
import uuid
from pathlib import Path
from typing import Any

from app.adapters.base import ToolAdapter
from app.config import get_settings
from app.models.schemas import HealthStatus, SourceType, ToolHealth, ValidationStatus, utcnow
from app.storage import db


class REINVENT4Adapter(ToolAdapter):
    id = "reinvent"
    name = "REINVENT4"
    category = "chemistry"
    required_config = ["REINVENT4_PYTHON or REINVENT4_BIN", "prior/checkpoint model files"]
    mode = "subprocess"

    def _jobs_dir(self) -> Path:
        d = Path(get_settings().cache_dir) / "reinvent"
        d.mkdir(parents=True, exist_ok=True)
        return d

    def _runner(self) -> tuple[str, list[str]] | None:
        s = get_settings()
        if s.reinvent4_python and Path(s.reinvent4_python).exists():
            return "python", [s.reinvent4_python, "-m", "reinvent"]
        if s.reinvent4_bin:
            import shutil
            if shutil.which(s.reinvent4_bin) or Path(s.reinvent4_bin).exists():
                return "bin", [s.reinvent4_bin]
        return None

    def health_check(self) -> ToolHealth:
        runner = self._runner()
        if runner:
            return ToolHealth(
                tool_id=self.id, name=self.name, category=self.category,
                status=HealthStatus.AVAILABLE, mode=self.mode,
                detail=f"REINVENT4 runner configured ({runner[0]}). Config generation + execution enabled.",
                required_config=self.required_config,
            )
        return ToolHealth(
            tool_id=self.id, name=self.name, category=self.category,
            status=HealthStatus.NOT_CONFIGURED, mode=self.mode,
            detail="REINVENT4 not configured. Config generation works; execution requires "
                   "REINVENT4_PYTHON or REINVENT4_BIN (see docs/TOOL_INTEGRATION.md).",
            required_config=self.required_config,
        )

    # -- create config ----------------------------------------------------
    def create_config(self, payload: dict[str, Any]) -> dict[str, Any]:
        job_id = f"rv-{uuid.uuid4().hex[:8]}"
        job_dir = self._jobs_dir() / job_id
        job_dir.mkdir(parents=True, exist_ok=True)
        weights = payload.get("scoring_weights", {}) or {}
        target = payload.get("target_name", "EGFR")
        max_molecules = int(payload.get("max_molecules", 100))
        config_path = job_dir / "sampling.toml"
        config_path.write_text(self._render_toml(target, weights, max_molecules, job_dir))

        db.insert("reinvent_jobs", {
            "id": job_id, "project_id": payload.get("project_id"), "created_at": utcnow(),
            "status": "config_created", "config_path": str(config_path),
            "target": target, "source_type": SourceType.CONFIGURED_BUT_NOT_RUN.value,
        })
        runner = self._runner()
        return {
            "tool_name": self.name, "source": self.name,
            "source_type": SourceType.CONFIGURED_BUT_NOT_RUN.value,
            "input_summary": f"target={target}, max_molecules={max_molecules}",
            "output_summary": f"REINVENT4 config written to {config_path.name}. "
                              + ("Runner configured — POST /api/reinvent/run to execute."
                                 if runner else "No runner configured; config is ready for a REINVENT4 install."),
            "validation_status": ValidationStatus.PASSED.value,
            "config_path": str(config_path), "job_id": job_id, "status": "config_created",
            "generated_smiles": [], "logs": [f"config generated for {target}"],
            "errors": [], "warnings": [] if runner else ["Execution requires REINVENT4_PYTHON/BIN — config only."],
        }

    def _render_toml(self, target: str, weights: dict[str, float], max_molecules: int, job_dir: Path) -> str:
        w = {
            "qed": weights.get("qed", 0.2),
            "rdkit_validity": weights.get("rdkit_validity", 0.2),
            "admet": weights.get("admet", 0.2),
            "novelty": weights.get("novelty", 0.2),
            "safety_penalty": weights.get("safety_penalty", 0.2),
        }
        out_smi = job_dir / "generated.smi"
        return f'''# REINVENT4 sampling configuration — generated by HelixForge AI
# Target context: {target}
# NOTE: `model_file` must point to a real REINVENT4 prior/checkpoint. This config
# is complete and valid; provide the model file to run.
run_type = "sampling"
device = "cpu"
json_out_config = "{job_dir / 'sampling.json'}"

[parameters]
model_file = "priors/reinvent.prior"   # <-- set to your REINVENT4 prior
output_file = "{out_smi}"
num_smiles = {max_molecules}
unique_molecules = true
randomize_smiles = true

# Scoring profile derived from request weights (transfer/RL scoring reference).
# Weights: QED={w['qed']} validity={w['rdkit_validity']} ADMET={w['admet']} novelty={w['novelty']} safety={w['safety_penalty']}
[scoring]
type = "geometric_mean"

[[scoring.component]]
[scoring.component.QED]
[[scoring.component.QED.endpoint]]
name = "QED"
weight = {w['qed']}

[[scoring.component]]
[scoring.component.custom_alerts]   # safety penalty: structural alerts
[[scoring.component.custom_alerts.endpoint]]
name = "safety_penalty"
weight = {w['safety_penalty']}

[[scoring.component]]
[scoring.component.MolecularWeight]  # ADMET-adjacent physchem guard
[[scoring.component.MolecularWeight.endpoint]]
name = "ADMET_physchem"
weight = {w['admet']}
transform.type = "double_sigmoid"
transform.high = 500.0
transform.low = 200.0
transform.coef_div = 500.0
transform.coef_si = 20.0
transform.coef_se = 20.0
'''

    # -- run --------------------------------------------------------------
    def run(self, payload: dict[str, Any]) -> dict[str, Any]:
        config_path = payload.get("config_path", "")
        summary = f"config={Path(config_path).name if config_path else '(none)'}"
        runner = self._runner()
        if not config_path or not Path(config_path).exists():
            return self._error(summary, [f"Config not found: {config_path}. Call create-config first."])
        if not runner:
            return {
                "tool_name": self.name, "source": self.name,
                "source_type": SourceType.CONFIGURED_BUT_NOT_RUN.value,
                "input_summary": summary,
                "output_summary": "REINVENT4 runner not configured; config is ready but was not executed.",
                "validation_status": ValidationStatus.SKIPPED.value,
                "config_path": config_path, "job_id": "", "status": "not_run",
                "generated_smiles": [], "logs": [],
                "errors": [], "warnings": ["Set REINVENT4_PYTHON or REINVENT4_BIN to execute. No fabricated output."],
            }
        try:
            cmd = runner[1] + [config_path]
            proc = subprocess.run(cmd, capture_output=True, text=True, timeout=get_settings().timeout_seconds * 20)
            logs = (proc.stdout + "\n" + proc.stderr).splitlines()[-40:]
            if proc.returncode != 0:
                return self._error(summary, [f"REINVENT4 exit {proc.returncode}"], logs=logs)
            # Parse output file referenced by config.
            smiles = self._read_output_from_config(config_path)
            parsed = self.parse_results({"smiles": smiles})
            return {
                "tool_name": self.name, "source": self.name,
                "source_type": SourceType.REAL_TOOL_OUTPUT.value,
                "input_summary": summary,
                "output_summary": f"REINVENT4 generated {len(smiles)} SMILES; {parsed.get('valid_count', 0)} valid (RDKit).",
                "validation_status": ValidationStatus.PASSED.value,
                "config_path": config_path, "job_id": f"rv-run-{uuid.uuid4().hex[:6]}", "status": "complete",
                "generated_smiles": smiles[:200], "valid_count": parsed.get("valid_count"),
                "logs": logs, "errors": [], "warnings": [],
            }
        except Exception as exc:
            return self._error(summary, [f"{type(exc).__name__}: {exc}"])

    def _read_output_from_config(self, config_path: str) -> list[str]:
        text = Path(config_path).read_text()
        out_file = None
        for line in text.splitlines():
            if line.strip().startswith("output_file"):
                out_file = line.split("=", 1)[1].strip().strip('"')
                break
        if out_file and Path(out_file).exists():
            return [ln.split()[0] for ln in Path(out_file).read_text().splitlines() if ln.strip()]
        return []

    # -- parse results ----------------------------------------------------
    def parse_results(self, payload: dict[str, Any]) -> dict[str, Any]:
        smiles = payload.get("smiles", [])
        if isinstance(smiles, str):
            smiles = [s for s in smiles.splitlines() if s.strip()]
        valid = 0
        try:
            from app.adapters.rdkit_adapter import RDKitAdapter, rdkit_available
            if rdkit_available():
                rd = RDKitAdapter()
                for smi in smiles:
                    r = rd.run({"operation": "validate", "smiles": smi})
                    if r.get("valid"):
                        valid += 1
        except Exception:
            pass
        return {
            "tool_name": self.name, "source": self.name,
            "source_type": SourceType.REAL_TOOL_OUTPUT.value if smiles else SourceType.CONFIGURED_BUT_NOT_RUN.value,
            "input_summary": f"{len(smiles)} SMILES to parse",
            "output_summary": f"Parsed {len(smiles)} SMILES; {valid} valid by RDKit.",
            "validation_status": ValidationStatus.PASSED.value if smiles else ValidationStatus.SKIPPED.value,
            "generated_smiles": smiles[:200], "valid_count": valid,
            "errors": [], "warnings": [],
        }

    def get_job(self, job_id: str) -> dict[str, Any] | None:
        return db.get("reinvent_jobs", job_id)

    def _error(self, summary: str, errors: list[str], logs: list[str] | None = None) -> dict[str, Any]:
        return {
            "tool_name": self.name, "source": self.name,
            "source_type": SourceType.TOOL_ERROR.value,
            "input_summary": summary,
            "output_summary": "REINVENT4 step failed; no fabricated molecules returned.",
            "validation_status": ValidationStatus.FAILED.value,
            "config_path": "", "job_id": "", "status": "error",
            "generated_smiles": [], "logs": logs or [], "errors": errors, "warnings": [],
        }
